version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: ./django_dockerfile/Dockerfile.prod         

    env_file:
      - ./backend/fire_outbreak_project/.env.prod
    volumes:
      - media:/app/fire_outbreak_project/fire_outbreak_project/media
      - staticfiles:/app/fire_outbreak_project/fire_outbreak_project/staticfiles
      
    ports:
      - 8000:8000
    restart: unless-stopped

  nginx:
    build:
      context: ./nginx
      dockerfile: ./nginx_dockerfile/Dockerfile.prod
    volumes:
      - staticfiles:/app/fire_outbreak_project/fire_outbreak_project/staticfiles
      - media:/app/fire_outbreak_project/fire_outbreak_project/media
      - react_build:/usr/share/nginx/html
    ports:
      - 80:80
    depends_on:
      - frontend
    restart: unless-stopped


  frontend:
    build:
      context: ./frontend
      dockerfile: ./react_dockerfile/Dockerfile.prod
    volumes:
      - react_build:/app/build
    depends_on:
      - backend
    restart: 'no'

  redis:
    image: redis:latest
    ports:
      - 6379:6379
    restart: unless-stopped
    env_file:
      - ./backend/fire_outbreak_project/.env.prod
volumes:
  staticfiles:
  media:
  react_build:
