# Generated by Django 5.0.3 on 2024-08-14 19:52

import django.contrib.gis.db.models.fields
import django.contrib.gis.geos.point
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FireHydrants",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "region",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Region"
                    ),
                ),
                (
                    "district",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="District"
                    ),
                ),
                ("location", models.CharField(max_length=80, verbose_name="Location")),
                (
                    "station_id",
                    models.CharField(
                        default=0, max_length=80, verbose_name="Station ID"
                    ),
                ),
                ("condition", models.CharField(default=0, max_length=80)),
                ("type_of_hydrant", models.CharField(default=0, max_length=80)),
                (
                    "geom",
                    django.contrib.gis.db.models.fields.PointField(
                        default=django.contrib.gis.geos.point.Point(0.0, 0.0), srid=4326
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["geom"],
                        name="geom_gist_idx_firehydrants",
                        opclasses=["gist"],
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="FireIncident",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("region", models.CharField(max_length=100, verbose_name="Region")),
                ("district", models.CharField(max_length=100, verbose_name="District")),
                (
                    "loc",
                    django.contrib.gis.db.models.fields.PointField(
                        default=django.contrib.gis.geos.point.Point(0.0, 0.0), srid=4326
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["loc"],
                        name="loc_gist_idx_fireincidents",
                        opclasses=["gist"],
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="FireStations",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "region",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Region"
                    ),
                ),
                (
                    "district",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="District"
                    ),
                ),
                (
                    "emergency_phone_number",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Emergency Phone Number"
                    ),
                ),
                ("location", models.CharField(max_length=80, verbose_name="Location")),
                (
                    "station_id",
                    models.CharField(
                        default=0, max_length=80, verbose_name="Station ID"
                    ),
                ),
                (
                    "number_of_staff",
                    models.IntegerField(default=0, verbose_name="Number of Staff"),
                ),
                (
                    "number_of_fire_tender",
                    models.IntegerField(
                        default=0, verbose_name="Number of Fire Tender"
                    ),
                ),
                (
                    "number_of_water_tanker",
                    models.IntegerField(
                        default=0, verbose_name="Number of Water Tanker"
                    ),
                ),
                (
                    "number_of_timetable_ladder",
                    models.IntegerField(
                        default=0, verbose_name="Number of Timetable Ladder"
                    ),
                ),
                (
                    "number_of_recovery_track",
                    models.IntegerField(
                        default=0, verbose_name="Number of Recovery Track"
                    ),
                ),
                (
                    "number_of_portable_pumb",
                    models.IntegerField(
                        default=0, verbose_name="Number of Portable Pumb"
                    ),
                ),
                (
                    "number_of_deep_lift_pumb",
                    models.IntegerField(
                        default=0, verbose_name="Number of Deep Lift Pumb"
                    ),
                ),
                (
                    "number_of_power_unit",
                    models.IntegerField(default=0, verbose_name="Number of Power Unit"),
                ),
                (
                    "geom",
                    django.contrib.gis.db.models.fields.PointField(
                        default=django.contrib.gis.geos.point.Point(0.0, 0.0), srid=4326
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["geom"],
                        name="geom_gist_idx_firestations",
                        opclasses=["gist"],
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Roads",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("u", models.BigIntegerField(blank=True, null=True)),
                ("v", models.BigIntegerField(blank=True, null=True)),
                ("key", models.BigIntegerField(blank=True, null=True)),
                ("osmid", models.CharField(blank=True, max_length=80, null=True)),
                ("name", models.CharField(blank=True, max_length=80, null=True)),
                ("highway", models.CharField(blank=True, max_length=80, null=True)),
                ("oneway", models.IntegerField(blank=True, null=True)),
                ("reversed", models.CharField(blank=True, max_length=80, null=True)),
                ("length", models.FloatField(blank=True, null=True)),
                ("lanes", models.CharField(blank=True, max_length=80, null=True)),
                ("ref", models.CharField(blank=True, max_length=80, null=True)),
                ("junction", models.CharField(blank=True, max_length=80, null=True)),
                ("bridge", models.CharField(blank=True, max_length=80, null=True)),
                ("maxspeed", models.CharField(blank=True, max_length=80, null=True)),
                ("service", models.CharField(blank=True, max_length=80, null=True)),
                ("tunnel", models.CharField(blank=True, max_length=80, null=True)),
                ("access", models.CharField(blank=True, max_length=80, null=True)),
                (
                    "geom",
                    django.contrib.gis.db.models.fields.LineStringField(
                        blank=True, null=True, srid=4326
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["geom"], name="geom_gist_idx_roads", opclasses=["gist"]
                    )
                ],
            },
        ),
    ]
