# Generated by Django 5.0.3 on 2024-08-14 20:05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("fire_outbreak_app", "0001_initial"),
    ]

    operations = []
