# Generated by Django 5.0.3 on 2024-05-23 07:48

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fire_outbreak_app', '0003_alter_roads_geometry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roads',
            name='geometry',
            field=django.contrib.gis.db.models.fields.LineStringField(srid=4326),
        ),
    ]
