# Generated by Django 5.0.3 on 2024-05-25 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fire_outbreak_app', '0004_alter_roads_geometry'),
    ]

    operations = [
        migrations.RenameField(
            model_name='roads',
            old_name='geometry',
            new_name='geom',
        ),
        migrations.AlterField(
            model_name='roads',
            name='access',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='roads',
            name='bridge',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='roads',
            name='highway',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='roads',
            name='junction',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='roads',
            name='key',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='roads',
            name='lanes',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='roads',
            name='length',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='roads',
            name='maxspeed',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='roads',
            name='name',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='roads',
            name='oneway',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='roads',
            name='osmid',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='roads',
            name='ref',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='roads',
            name='reversed',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='roads',
            name='service',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='roads',
            name='tunnel',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='roads',
            name='u',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='roads',
            name='v',
            field=models.BigIntegerField(),
        ),
    ]
