# Generated by Django 5.0.3 on 2024-05-26 07:02

import django.contrib.gis.db.models.fields
from django.db import migrations, models
from django.contrib.gis.geos import Point


class Migration(migrations.Migration):

    dependencies = [
        ('fire_outbreak_app', '0005_rename_geometry_roads_geom_alter_roads_access_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='firehydrants',
            name='locality',
        ),
        migrations.RemoveField(
            model_name='firestations',
            name='locality',
        ),
        migrations.AddField(
            model_name='firehydrants',
            name='condition',
            field=models.CharField(default=0, max_length=80),
        ),
        migrations.AddField(
            model_name='firehydrants',
            name='geom',
            field=django.contrib.gis.db.models.fields.PointField(default=Point(0.0, 0.0), srid=4326),
        ),
        migrations.AddField(
            model_name='firehydrants',
            name='station_id',
            field=models.CharField(default=0, max_length=80, verbose_name='Station ID'),
        ),
        migrations.AddField(
            model_name='firehydrants',
            name='type_of_hydrant',
            field=models.CharField(default=0, max_length=80),
        ),
        migrations.AddField(
            model_name='firestations',
            name='geom',
            field=django.contrib.gis.db.models.fields.PointField(default=Point(0.0, 0.0), srid=4326),
        ),
        migrations.AddField(
            model_name='firestations',
            name='number_of_deep_lift_pumb',
            field=models.IntegerField(default=0, verbose_name='Number of Deep Lift Pumb'),
        ),
        migrations.AddField(
            model_name='firestations',
            name='number_of_fire_tender',
            field=models.IntegerField(default=0, verbose_name='Number of Fire Tender'),
        ),
        migrations.AddField(
            model_name='firestations',
            name='number_of_portable_pumb',
            field=models.IntegerField(default=0, verbose_name='Number of Portable Pumb'),
        ),
        migrations.AddField(
            model_name='firestations',
            name='number_of_power_unit',
            field=models.IntegerField(default=0, verbose_name='Number of Power Unit'),
        ),
        migrations.AddField(
            model_name='firestations',
            name='number_of_recovery_track',
            field=models.IntegerField(default=0, verbose_name='Number of Recovery Track'),
        ),
        migrations.AddField(
            model_name='firestations',
            name='number_of_staff',
            field=models.IntegerField(default=0, verbose_name='Number of Staff'),
        ),
        migrations.AddField(
            model_name='firestations',
            name='number_of_timetable_ladder',
            field=models.IntegerField(default=0, verbose_name='Number of Timetable Ladder'),
        ),
        migrations.AddField(
            model_name='firestations',
            name='number_of_water_tanker',
            field=models.IntegerField(default=0, verbose_name='Number of Water Tanker'),
        ),
        migrations.AddField(
            model_name='firestations',
            name='station_id',
            field=models.CharField(default=0, max_length=80, verbose_name='Station ID'),
        ),
        migrations.AlterField(
            model_name='firehydrants',
            name='district',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='District'),
        ),
        migrations.AlterField(
            model_name='firehydrants',
            name='location',
            field=models.CharField(max_length=80, verbose_name='Location'),
        ),
        migrations.AlterField(
            model_name='firehydrants',
            name='region',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Region'),
        ),
        migrations.AlterField(
            model_name='firestations',
            name='district',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='District'),
        ),
        migrations.AlterField(
            model_name='firestations',
            name='emergency_phone_number',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Emergency Phone Number'),
        ),
        migrations.AlterField(
            model_name='firestations',
            name='location',
            field=models.CharField(max_length=80, verbose_name='Location'),
        ),
        migrations.AlterField(
            model_name='firestations',
            name='region',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Region'),
        ),
    ]
