# Generated by Django 5.0.3 on 2024-05-26 07:13

import django.contrib.gis.db.models.fields
import django.contrib.gis.geos.point
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fire_outbreak_app', '0006_remove_firehydrants_locality_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firehydrants',
            name='geom',
            field=django.contrib.gis.db.models.fields.PointField(default=django.contrib.gis.geos.point.Point(0.0, 0.0), srid=4326),
        ),
        migrations.AlterField(
            model_name='fireincident',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(default=django.contrib.gis.geos.point.Point(0.0, 0.0), srid=4326),
        ),
        migrations.AlterField(
            model_name='firestations',
            name='geom',
            field=django.contrib.gis.db.models.fields.PointField(default=django.contrib.gis.geos.point.Point(0.0, 0.0), srid=4326),
        ),
    ]
