# Generated by Django 5.0.3 on 2024-05-26 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fire_outbreak_app', '0008_remove_fireincident_locality'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='firehydrants',
            index=models.Index(fields=['geom'], name='geom_gist_idx_firehydrants', opclasses=['gist']),
        ),
        migrations.AddIndex(
            model_name='firestations',
            index=models.Index(fields=['geom'], name='geom_gist_idx_firestations', opclasses=['gist']),
        ),
    ]
