# Generated by Django 5.0.3 on 2024-05-26 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fire_outbreak_app', '0009_firehydrants_geom_gist_idx_firehydrants_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fireincident',
            old_name='location',
            new_name='loc',
        ),
        migrations.AddIndex(
            model_name='fireincident',
            index=models.Index(fields=['loc'], name='loc_gist_idx_fireincidents', opclasses=['gist']),
        ),
    ]
