# Generated by Django 5.0.3 on 2024-05-26 11:16

import django.contrib.gis.db.models.fields
import django.contrib.gis.geos.point
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fire_outbreak_app', '0010_rename_location_fireincident_loc_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firestations',
            name='geom',
            field=django.contrib.gis.db.models.fields.PointField(default=django.contrib.gis.geos.point.Point(-1.0, 6.0), srid=4326),
        ),
    ]
